//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2012
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ubs.Collateral.Sre.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ubs.Collateral.Sre.Common.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing all locks for user {0} .
        /// </summary>
        public static string Application_ClearLockStatus {
            get {
                return ResourceManager.GetString("Application_ClearLockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize {0}.
        /// </summary>
        public static string Application_Customize {
            get {
                return ResourceManager.GetString("Application_Customize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit &apos;{0}&apos;.
        /// </summary>
        public static string Application_ExitApplication {
            get {
                return ResourceManager.GetString("Application_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized runtime environment supplied [{0}], should be either : {1}.
        /// </summary>
        public static string Application_InvalidArgument {
            get {
                return ResourceManager.GetString("Application_InvalidArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging Console - {0}.
        /// </summary>
        public static string Application_LoggingConsole {
            get {
                return ResourceManager.GetString("Application_LoggingConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Sprint {1} (Rev {2}).
        /// </summary>
        public static string Application_LoginDialogHeaderDev {
            get {
                return ResourceManager.GetString("Application_LoginDialogHeaderDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} (Revision {2}).
        /// </summary>
        public static string Application_LoginDialogHeaderProd {
            get {
                return ResourceManager.GetString("Application_LoginDialogHeaderProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your production WebSSO password.
        /// </summary>
        public static string Application_LoginPrompt {
            get {
                return ResourceManager.GetString("Application_LoginPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more Tibco settings are missing for {0} [{1}].
        /// </summary>
        public static string Application_MissingTibcoSetting {
            get {
                return ResourceManager.GetString("Application_MissingTibcoSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock status is being retrieved, please wait.
        /// </summary>
        public static string Application_RetrieveLockStatus {
            get {
                return ResourceManager.GetString("Application_RetrieveLockStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RulesEngine.
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm you wish to paste {0} item(s) into the {1} cell ?.
        /// </summary>
        public static string Clipboard_ConfirmCopy {
            get {
                return ResourceManager.GetString("Clipboard_ConfirmCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected to clipboard.
        /// </summary>
        public static string Clipboard_Copy {
            get {
                return ResourceManager.GetString("Clipboard_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error attempting to paste into cell {0}{1}{2}{3}{4}.
        /// </summary>
        public static string Clipboard_Failed2Paste {
            get {
                return ResourceManager.GetString("Clipboard_Failed2Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This occurred on  row {0} found in the clipboard buffer.
        /// </summary>
        public static string Clipboard_FailedElement {
            get {
                return ResourceManager.GetString("Clipboard_FailedElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The row that has been selected for copying to clipboard  contains no meaningful information..
        /// </summary>
        public static string Clipboard_FilterSelected {
            get {
                return ResourceManager.GetString("Clipboard_FilterSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records selected.
        /// </summary>
        public static string Clipboard_NothingSelected {
            get {
                return ResourceManager.GetString("Clipboard_NothingSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have attempted to paste in {0} row(s). Only a single item is supported!.
        /// </summary>
        public static string Clipboard_PasteMoreThenOneRowError {
            get {
                return ResourceManager.GetString("Clipboard_PasteMoreThenOneRowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only paste values into the filter row..
        /// </summary>
        public static string Clipboard_PasteOnlyInFilterRow {
            get {
                return ResourceManager.GetString("Clipboard_PasteOnlyInFilterRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only paste into the Filter Bar and the column must be a non-checkbox listbox..
        /// </summary>
        public static string Clipboard_PasteOnlySupportedInDynamicFilter {
            get {
                return ResourceManager.GetString("Clipboard_PasteOnlySupportedInDynamicFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot paste into  {0} as this is a readonly cell..
        /// </summary>
        public static string Clipboard_Readonly {
            get {
                return ResourceManager.GetString("Clipboard_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To paste into the grid, position your cursor on a single cell or row.
        /// </summary>
        public static string Clipboard_SelectSingleCellOrRow {
            get {
                return ResourceManager.GetString("Clipboard_SelectSingleCellOrRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To paste a value, position your cursor on the Filter Bar and ensure only a single column is selected..
        /// </summary>
        public static string Clipboard_SelectSingleCellOrRowForPaste {
            get {
                return ResourceManager.GetString("Clipboard_SelectSingleCellOrRowForPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ensure that only TEXT is pasted into this cell.
        /// </summary>
        public static string Clipboard_TextRequired {
            get {
                return ResourceManager.GetString("Clipboard_TextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with {1} columns.
        /// </summary>
        public static string ColumnChooser_DefaultViewName {
            get {
                return ResourceManager.GetString("ColumnChooser_DefaultViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a valid non-null grid !.
        /// </summary>
        public static string ColumnChooser_GridNullError {
            get {
                return ResourceManager.GetString("ColumnChooser_GridNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please {0} a valid View name.
        /// </summary>
        public static string ColumnChooser_InvalidViewName {
            get {
                return ResourceManager.GetString("ColumnChooser_InvalidViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the VIEW profile that you wish to load.
        /// </summary>
        public static string ColumnChooser_LoadTitle {
            get {
                return ResourceManager.GetString("ColumnChooser_LoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items have been added to the Current pane, View cannot be saved..
        /// </summary>
        public static string ColumnChooser_NoItems {
            get {
                return ResourceManager.GetString("ColumnChooser_NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No View profiles currently exist. Save a profile first..
        /// </summary>
        public static string ColumnChooser_NoProfilesExist {
            get {
                return ResourceManager.GetString("ColumnChooser_NoProfilesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Views that you wish to remove.
        /// </summary>
        public static string ColumnChooser_NoSelectionMade {
            get {
                return ResourceManager.GetString("ColumnChooser_NoSelectionMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem removing selected views. No views removed..
        /// </summary>
        public static string ColumnChooser_NoViewRemoved {
            get {
                return ResourceManager.GetString("ColumnChooser_NoViewRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {0} view(s) have been removed.
        /// </summary>
        public static string ColumnChooser_OnlyXViewRemoved {
            get {
                return ResourceManager.GetString("ColumnChooser_OnlyXViewRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View name already exists, overwriite ?.
        /// </summary>
        public static string ColumnChooser_Overwrite {
            get {
                return ResourceManager.GetString("ColumnChooser_Overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the View that you wish to save.
        /// </summary>
        public static string ColumnChooser_SaveTitle {
            get {
                return ResourceManager.GetString("ColumnChooser_SaveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Columns ....
        /// </summary>
        public static string ColumnChooser_SelectColumns {
            get {
                return ResourceManager.GetString("ColumnChooser_SelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To re-order, please select a single row only.
        /// </summary>
        public static string ColumnChooser_SelectSingleColumn {
            get {
                return ResourceManager.GetString("ColumnChooser_SelectSingleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the views you wish to remove.
        /// </summary>
        public static string ColumnChooser_ViewMaintenanceTitle {
            get {
                return ResourceManager.GetString("ColumnChooser_ViewMaintenanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All selected views have successfully been removed.
        /// </summary>
        public static string ColumnChooser_ViewRemoved {
            get {
                return ResourceManager.GetString("ColumnChooser_ViewRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &lt;{0}&gt; section is not defined in the application configuration file..
        /// </summary>
        public static string Configuration_InvalidSection {
            get {
                return ResourceManager.GetString("Configuration_InvalidSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writeable_Config_file.xml.
        /// </summary>
        public static string Configuration_WriteableConfigFile {
            get {
                return ResourceManager.GetString("Configuration_WriteableConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort operation ?.
        /// </summary>
        public static string Dialog_AbortOperation {
            get {
                return ResourceManager.GetString("Dialog_AbortOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Dialog_ErrorTitle {
            get {
                return ResourceManager.GetString("Dialog_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Dialog_InformationTitle {
            get {
                return ResourceManager.GetString("Dialog_InformationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Dialog_QuestionTitle {
            get {
                return ResourceManager.GetString("Dialog_QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Dialog_WarningTitle {
            get {
                return ResourceManager.GetString("Dialog_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal argument has been supplied : .
        /// </summary>
        public static string Exception_ArgumentException {
            get {
                return ResourceManager.GetString("Exception_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument supplied is not a GridControl:.
        /// </summary>
        public static string Exception_ArgumentNotGridControl {
            get {
                return ResourceManager.GetString("Exception_ArgumentNotGridControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument supplied is not a GridDataBoundGridControl:.
        /// </summary>
        public static string Exception_ArgumentNotGridDataBoundGridControl {
            get {
                return ResourceManager.GetString("Exception_ArgumentNotGridDataBoundGridControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument supplied is not a GridGroupingControl:.
        /// </summary>
        public static string Exception_ArgumentNotGridGroupingControl {
            get {
                return ResourceManager.GetString("Exception_ArgumentNotGridGroupingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to read from stream :{0}.
        /// </summary>
        public static string Exception_CannotReadStream {
            get {
                return ResourceManager.GetString("Exception_CannotReadStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UBS AG - XXXX.
        /// </summary>
        public static string Exception_DialogTitle {
            get {
                return ResourceManager.GetString("Exception_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load view :{0}{1}{2}.
        /// </summary>
        public static string Exception_ErrorLoadingView {
            get {
                return ResourceManager.GetString("Exception_ErrorLoadingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to {0} this View. Is the view name valid ?.
        /// </summary>
        public static string Exception_ErrorSavingView {
            get {
                return ResourceManager.GetString("Exception_ErrorSavingView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected column : {0} in the schema !.
        /// </summary>
        public static string Exception_ExpectedSchemaColumn {
            get {
                return ResourceManager.GetString("Exception_ExpectedSchemaColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grid to persist has not been defined (Null).
        /// </summary>
        public static string Exception_GridNotSet {
            get {
                return ResourceManager.GetString("Exception_GridNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following characters cannot be entered in {0} field :.
        /// </summary>
        public static string Exception_InvalidCharacters {
            get {
                return ResourceManager.GetString("Exception_InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Characters.
        /// </summary>
        public static string Exception_InvalidCharactersHeader {
            get {
                return ResourceManager.GetString("Exception_InvalidCharactersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to  load grid schema :{0}.
        /// </summary>
        public static string Exception_LoadGridSchema {
            get {
                return ResourceManager.GetString("Exception_LoadGridSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field   [{0}]  cannot exceed {0} characters.
        /// </summary>
        public static string Exception_MaxCharacters {
            get {
                return ResourceManager.GetString("Exception_MaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Characters.
        /// </summary>
        public static string Exception_MaxCharactersHeader {
            get {
                return ResourceManager.GetString("Exception_MaxCharactersHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code has not been implemented for this action :.
        /// </summary>
        public static string Exception_NotImplemented {
            get {
                return ResourceManager.GetString("Exception_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please override this base method and provide the descendant functionality.
        /// </summary>
        public static string Exception_PleaseOverride {
            get {
                return ResourceManager.GetString("Exception_PleaseOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program logic exception with message &apos;{0}&apos;.
        /// </summary>
        public static string Exception_ProgramLogicError {
            get {
                return ResourceManager.GetString("Exception_ProgramLogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program logic exception with message &apos;{0}&apos;.
        /// </summary>
        public static string Exception_ProgramLogicError1 {
            get {
                return ResourceManager.GetString("Exception_ProgramLogicError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to deserialize the Grid LNF.
        /// </summary>
        public static string Exception_RestoreLNF {
            get {
                return ResourceManager.GetString("Exception_RestoreLNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to deserialize the Grid Schema.
        /// </summary>
        public static string Exception_RestoreSchema {
            get {
                return ResourceManager.GetString("Exception_RestoreSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to create grid schema :{0}.
        /// </summary>
        public static string Exception_SaveGridSchema {
            get {
                return ResourceManager.GetString("Exception_SaveGridSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to serialize the Grid LNF.
        /// </summary>
        public static string Exception_SaveLNF {
            get {
                return ResourceManager.GetString("Exception_SaveLNF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to serialize the Grid Schema.
        /// </summary>
        public static string Exception_SaveSchema {
            get {
                return ResourceManager.GetString("Exception_SaveSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to read the Grid Schema/LNF file.
        /// </summary>
        public static string Exception_SchemaReadError {
            get {
                return ResourceManager.GetString("Exception_SchemaReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem to create the following directory :{0}.
        /// </summary>
        public static string Exception_UnableToCreateDirectory {
            get {
                return ResourceManager.GetString("Exception_UnableToCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem to create the following file:.
        /// </summary>
        public static string Exception_UnableToCreateFile {
            get {
                return ResourceManager.GetString("Exception_UnableToCreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred.
        /// </summary>
        public static string Exception_UnknownMessage {
            get {
                return ResourceManager.GetString("Exception_UnknownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no rows to export.
        /// </summary>
        public static string Export_GridExportedNoRows {
            get {
                return ResourceManager.GetString("Export_GridExportedNoRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The grid has successfully been exported to Excel.
        /// </summary>
        public static string Export_GridExportedOk {
            get {
                return ResourceManager.GetString("Export_GridExportedOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Completed.
        /// </summary>
        public static string Export_GridExportedTitle {
            get {
                return ResourceManager.GetString("Export_GridExportedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  {0} rows successfully exported to Excel.
        /// </summary>
        public static string Export_Header1 {
            get {
                return ResourceManager.GetString("Export_Header1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows exported : {0}.
        /// </summary>
        public static string Export_Header2 {
            get {
                return ResourceManager.GetString("Export_Header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to {0} job has been submitted. You will be notified once this completes.
        /// </summary>
        public static string Export_JobSubmitted {
            get {
                return ResourceManager.GetString("Export_JobSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Scheduled.
        /// </summary>
        public static string Export_JobSubmittedTitle {
            get {
                return ResourceManager.GetString("Export_JobSubmittedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid is empty or there was an error exporting trades.
        /// </summary>
        public static string Export_NoTradesToExport {
            get {
                return ResourceManager.GetString("Export_NoTradesToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel is in progress. Excel will be launched once done..
        /// </summary>
        public static string Export_QueuedMessage {
            get {
                return ResourceManager.GetString("Export_QueuedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available:{0}.
        /// </summary>
        public static string Filter_Availableitems {
            get {
                return ResourceManager.GetString("Filter_Availableitems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected:{0}.
        /// </summary>
        public static string Filter_CheckedItems {
            get {
                return ResourceManager.GetString("Filter_CheckedItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to clear all existing filters on this grid ?.
        /// </summary>
        public static string Filter_ClearAllFilters {
            get {
                return ResourceManager.GetString("Filter_ClearAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (Current Filter).
        /// </summary>
        public static string Filter_CurrentFilter {
            get {
                return ResourceManager.GetString("Filter_CurrentFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently filters exist.
        /// </summary>
        public static string Filter_CurrentlyFiltersExist {
            get {
                return ResourceManager.GetString("Filter_CurrentlyFiltersExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d MMM yyyy.
        /// </summary>
        public static string Filter_DateFormat {
            get {
                return ResourceManager.GetString("Filter_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to r.
        /// </summary>
        public static string Filter_DateTimeFormat {
            get {
                return ResourceManager.GetString("Filter_DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} item(s) above not shown because of other column filters.
        /// </summary>
        public static string Filter_ExtendedFilterMessage {
            get {
                return ResourceManager.GetString("Filter_ExtendedFilterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of filters currently in use is .
        /// </summary>
        public static string Filter_FilterCount {
            get {
                return ResourceManager.GetString("Filter_FilterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters already applied to column :.
        /// </summary>
        public static string Filter_FiltersApplied2Column {
            get {
                return ResourceManager.GetString("Filter_FiltersApplied2Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters for column : .
        /// </summary>
        public static string Filter_FiltersForColumn {
            get {
                return ResourceManager.GetString("Filter_FiltersForColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupingControl has not been set.
        /// </summary>
        public static string Filter_InvalidOperation_GGCNotSet {
            get {
                return ResourceManager.GetString("Filter_InvalidOperation_GGCNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to choose from.
        /// </summary>
        public static string Filter_ItemsToChooseFrom {
            get {
                return ResourceManager.GetString("Filter_ItemsToChooseFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no filters to clear.
        /// </summary>
        public static string Filter_NoFiltersToClear {
            get {
                return ResourceManager.GetString("Filter_NoFiltersToClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid already filtered by item(s) above.
        /// </summary>
        public static string Filter_NoMoreSelections {
            get {
                return ResourceManager.GetString("Filter_NoMoreSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found - nothing to filter.
        /// </summary>
        public static string Filter_NoRecordsFound {
            get {
                return ResourceManager.GetString("Filter_NoRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filter values selected  - Select one or more items then press OK..
        /// </summary>
        public static string Filter_NoSelectionMade {
            get {
                return ResourceManager.GetString("Filter_NoSelectionMade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to use existing filters ?.
        /// </summary>
        public static string Filter_UseExistingFilters {
            get {
                return ResourceManager.GetString("Filter_UseExistingFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort load ?.
        /// </summary>
        public static string Grid_AbortLoad {
            get {
                return ResourceManager.GetString("Grid_AbortLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled..
        /// </summary>
        public static string Grid_CancelledTitle {
            get {
                return ResourceManager.GetString("Grid_CancelledTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation request pending....
        /// </summary>
        public static string Grid_CancelLoad {
            get {
                return ResourceManager.GetString("Grid_CancelLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be patient.
        /// </summary>
        public static string Grid_CancelLoadTitle {
            get {
                return ResourceManager.GetString("Grid_CancelLoadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation cancelled.{0}Trades shown  {1}  out of a possible {2}.
        /// </summary>
        public static string Grid_OperationCancelled {
            get {
                return ResourceManager.GetString("Grid_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string Grid_SuccessTitle {
            get {
                return ResourceManager.GetString("Grid_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services running smoothly.
        /// </summary>
        public static string Heartbeat_AvailableHeader {
            get {
                return ResourceManager.GetString("Heartbeat_AvailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All backend services are running without interruption.
        /// </summary>
        public static string Heartbeat_AvailableTooltip {
            get {
                return ResourceManager.GetString("Heartbeat_AvailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend servers are down - you have limited services!.
        /// </summary>
        public static string Heartbeat_ServersDownMessage {
            get {
                return ResourceManager.GetString("Heartbeat_ServersDownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more connections with backend servers has been lost, disruption may occur.
        /// </summary>
        public static string Heartbeat_ServersDownSplashMessage {
            get {
                return ResourceManager.GetString("Heartbeat_ServersDownSplashMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Unavailable.
        /// </summary>
        public static string Heartbeat_UnavailableHeader {
            get {
                return ResourceManager.GetString("Heartbeat_UnavailableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more backend services is unavailable, disruption may occur.
        /// </summary>
        public static string Heartbeat_UnavailableTooltip {
            get {
                return ResourceManager.GetString("Heartbeat_UnavailableTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow Services.
        /// </summary>
        public static string Heartbeat_UnknownHeader {
            get {
                return ResourceManager.GetString("Heartbeat_UnknownHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown status code has been returned ??.
        /// </summary>
        public static string Heartbeat_UnknownTooltip {
            get {
                return ResourceManager.GetString("Heartbeat_UnknownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required.
        /// </summary>
        public static string InputForm_ValueRequired {
            get {
                return ResourceManager.GetString("InputForm_ValueRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GroupingControl has not been set.
        /// </summary>
        public static string InvalidOperation_GGCNotSet {
            get {
                return ResourceManager.GetString("InvalidOperation_GGCNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column list has not been set [DDLB/Dynamic].
        /// </summary>
        public static string InvalidOperation_NoColumnSet {
            get {
                return ResourceManager.GetString("InvalidOperation_NoColumnSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Keyboard_CapsOff {
            get {
                return ResourceManager.GetString("Keyboard_CapsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPS.
        /// </summary>
        public static string Keyboard_CapsOn {
            get {
                return ResourceManager.GetString("Keyboard_CapsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having Caps Lock on may cause you to enter your password incorrectly.
        /// </summary>
        public static string Keyboard_CapsOnMessageContent {
            get {
                return ResourceManager.GetString("Keyboard_CapsOnMessageContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should press Caps Lock to turn it off before entering your password.
        /// </summary>
        public static string Keyboard_CapsOnMessageFooter {
            get {
                return ResourceManager.GetString("Keyboard_CapsOnMessageFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps lock is on.
        /// </summary>
        public static string Keyboard_CapsOnMessageHeader {
            get {
                return ResourceManager.GetString("Keyboard_CapsOnMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OVR.
        /// </summary>
        public static string Keyboard_InsertOff {
            get {
                return ResourceManager.GetString("Keyboard_InsertOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INS.
        /// </summary>
        public static string Keyboard_InsertOn {
            get {
                return ResourceManager.GetString("Keyboard_InsertOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Keyboard_NumOff {
            get {
                return ResourceManager.GetString("Keyboard_NumOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUM.
        /// </summary>
        public static string Keyboard_NumOn {
            get {
                return ResourceManager.GetString("Keyboard_NumOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Keyboard_ScrollOff {
            get {
                return ResourceManager.GetString("Keyboard_ScrollOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCROLL.
        /// </summary>
        public static string Keyboard_ScrollOn {
            get {
                return ResourceManager.GetString("Keyboard_ScrollOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel logging in to {0}.
        /// </summary>
        public static string Login_CancelTTT {
            get {
                return ResourceManager.GetString("Login_CancelTTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dev.
        /// </summary>
        public static string Login_DevEnvironment {
            get {
                return ResourceManager.GetString("Login_DevEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEVMODE.
        /// </summary>
        public static string Login_DevMode {
            get {
                return ResourceManager.GetString("Login_DevMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dev_os.
        /// </summary>
        public static string Login_DevOffshoreEnvironment {
            get {
                return ResourceManager.GetString("Login_DevOffshoreEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENV.
        /// </summary>
        public static string Login_EnvironmentKey {
            get {
                return ResourceManager.GetString("Login_EnvironmentKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linux_dev_fi.
        /// </summary>
        public static string Login_LinuxDevFiEnvironment {
            get {
                return ResourceManager.GetString("Login_LinuxDevFiEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linux_dev_os.
        /// </summary>
        public static string Login_LinuxDevOsEnvironment {
            get {
                return ResourceManager.GetString("Login_LinuxDevOsEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linux_prod.
        /// </summary>
        public static string Login_LinuxProdEnvironment {
            get {
                return ResourceManager.GetString("Login_LinuxProdEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linux_uat.
        /// </summary>
        public static string Login_LinuxUatEnvironment {
            get {
                return ResourceManager.GetString("Login_LinuxUatEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Not logged in&gt;.
        /// </summary>
        public static string Login_NotLoggedIn {
            get {
                return ResourceManager.GetString("Login_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to login using credentials supplied.
        /// </summary>
        public static string Login_OkTTT {
            get {
                return ResourceManager.GetString("Login_OkTTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string Login_PasswordHelp {
            get {
                return ResourceManager.GetString("Login_PasswordHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to prod.
        /// </summary>
        public static string Login_ProdEnvironment {
            get {
                return ResourceManager.GetString("Login_ProdEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uat.
        /// </summary>
        public static string Login_UatEnvironment {
            get {
                return ResourceManager.GetString("Login_UatEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UID.
        /// </summary>
        public static string Login_UIDKey {
            get {
                return ResourceManager.GetString("Login_UIDKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your LDAP ID.
        /// </summary>
        public static string Login_UserIDHelp {
            get {
                return ResourceManager.GetString("Login_UserIDHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Login_VersionString {
            get {
                return ResourceManager.GetString("Login_VersionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLICATION ERROR.
        /// </summary>
        public static string Msg_AppErr {
            get {
                return ResourceManager.GetString("Msg_AppErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *********************************************.
        /// </summary>
        public static string Msg_Asterisk {
            get {
                return ResourceManager.GetString("Msg_Asterisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to    DEBUG INFO     .
        /// </summary>
        public static string Msg_DInfo {
            get {
                return ResourceManager.GetString("Msg_DInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distinguished Name is: {0}{1}.
        /// </summary>
        public static string Msg_DstngshdNm {
            get {
                return ResourceManager.GetString("Msg_DstngshdNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment = {0}.
        /// </summary>
        public static string Msg_Env {
            get {
                return ResourceManager.GetString("Msg_Env", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **ERROR**.
        /// </summary>
        public static string Msg_ErrTtl {
            get {
                return ResourceManager.GetString("Msg_ErrTtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name: {0}{1}.
        /// </summary>
        public static string Msg_Host {
            get {
                return ResourceManager.GetString("Msg_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host address {0}: {1}{2}.
        /// </summary>
        public static string Msg_HostAddr {
            get {
                return ResourceManager.GetString("Msg_HostAddr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INNER EXCEPION {0}{1}{2}.
        /// </summary>
        public static string Msg_InExp {
            get {
                return ResourceManager.GetString("Msg_InExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address: {0}{1}.
        /// </summary>
        public static string Msg_Mlddrs {
            get {
                return ResourceManager.GetString("Msg_Mlddrs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Id: {0}{1}.
        /// </summary>
        public static string Msg_Mplyd {
            get {
                return ResourceManager.GetString("Msg_Mplyd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MESSAGE {0}{1}{2}.
        /// </summary>
        public static string Msg_Msg {
            get {
                return ResourceManager.GetString("Msg_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _________________.
        /// </summary>
        public static string Msg_Score {
            get {
                return ResourceManager.GetString("Msg_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;(Version [ {1} ] )&apos; shutdown in progress for {2}.
        /// </summary>
        public static string Msg_Shutdown {
            get {
                return ResourceManager.GetString("Msg_Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ***System Info***.
        /// </summary>
        public static string Msg_SInfoTtl {
            get {
                return ResourceManager.GetString("Msg_SInfoTtl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOURCE {0}{1}{2}.
        /// </summary>
        public static string Msg_Src {
            get {
                return ResourceManager.GetString("Msg_Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;(Version [ {1} ] )&apos; startup in progress for {2}.
        /// </summary>
        public static string Msg_Startup {
            get {
                return ResourceManager.GetString("Msg_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STACK TRACE {0}{1}{2}.
        /// </summary>
        public static string Msg_StckTrc {
            get {
                return ResourceManager.GetString("Msg_StckTrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username: {0}{1}.
        /// </summary>
        public static string Msg_User {
            get {
                return ResourceManager.GetString("Msg_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Principal Name: {0}{1}.
        /// </summary>
        public static string Msg_UsrPrncplNm {
            get {
                return ResourceManager.GetString("Msg_UsrPrncplNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice Telephone Number: {0}{1}.
        /// </summary>
        public static string Msg_VcTlNm {
            get {
                return ResourceManager.GetString("Msg_VcTlNm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version = {0}.
        /// </summary>
        public static string Msg_Version {
            get {
                return ResourceManager.GetString("Msg_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to remove existing pinned columns ?.
        /// </summary>
        public static string Pin_RemovePinColumns {
            get {
                return ResourceManager.GetString("Pin_RemovePinColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Popup_Clear {
            get {
                return ResourceManager.GetString("Popup_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Pinned Columns.
        /// </summary>
        public static string Popup_ClearPin {
            get {
                return ResourceManager.GetString("Popup_ClearPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Popup_Copy {
            get {
                return ResourceManager.GetString("Popup_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy All.
        /// </summary>
        public static string Popup_CopyAll {
            get {
                return ResourceManager.GetString("Popup_CopyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Popup_Export {
            get {
                return ResourceManager.GetString("Popup_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string Popup_Find {
            get {
                return ResourceManager.GetString("Popup_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to column ....
        /// </summary>
        public static string Popup_JumpColumn {
            get {
                return ResourceManager.GetString("Popup_JumpColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Popup_LoadView {
            get {
                return ResourceManager.GetString("Popup_LoadView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin columns.
        /// </summary>
        public static string Popup_Pin {
            get {
                return ResourceManager.GetString("Popup_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Popup_Print {
            get {
                return ResourceManager.GetString("Popup_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Preview.
        /// </summary>
        public static string Popup_PrintPreview {
            get {
                return ResourceManager.GetString("Popup_PrintPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row selection.
        /// </summary>
        public static string Popup_RowSelection {
            get {
                return ResourceManager.GetString("Popup_RowSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Popup_SaveView {
            get {
                return ResourceManager.GetString("Popup_SaveView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns....
        /// </summary>
        public static string Popup_SelectColumns {
            get {
                return ResourceManager.GetString("Popup_SelectColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Portfolio Pricing Job.
        /// </summary>
        public static string PortfolioForm_Title {
            get {
                return ResourceManager.GetString("PortfolioForm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home drive is not set - defaulting to: .
        /// </summary>
        public static string Preference_HomeDriveNotSet {
            get {
                return ResourceManager.GetString("Preference_HomeDriveNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE_SET_TO_APP_NAME.
        /// </summary>
        public static string Preferences_DefaultConfigDirectory {
            get {
                return ResourceManager.GetString("Preferences_DefaultConfigDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /dnp/{0}/guiconfig/.
        /// </summary>
        public static string Preferences_DefaultPrivatePath {
            get {
                return ResourceManager.GetString("Preferences_DefaultPrivatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GridModel.
        /// </summary>
        public static string Preferences_DefaultSchemaName {
            get {
                return ResourceManager.GetString("Preferences_DefaultSchemaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .Schema.XML.
        /// </summary>
        public static string Preferences_DefaultSchemaNameExtension {
            get {
                return ResourceManager.GetString("Preferences_DefaultSchemaNameExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CustomDefaultView_{0}_Columns.
        /// </summary>
        public static string Preferences_DefaultViewName {
            get {
                return ResourceManager.GetString("Preferences_DefaultViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to load user preferences file  [{0}].
        /// </summary>
        public static string Preferences_LoadError {
            get {
                return ResourceManager.GetString("Preferences_LoadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Sent.
        /// </summary>
        public static string Progress_RequestHeader {
            get {
                return ResourceManager.GetString("Progress_RequestHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema files successfully removed from your home drive..
        /// </summary>
        public static string Schema_RemovedFiles {
            get {
                return ResourceManager.GetString("Schema_RemovedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Cleanup.
        /// </summary>
        public static string Schema_RemovedFilesHeader {
            get {
                return ResourceManager.GetString("Schema_RemovedFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you do not have access to this part of the system..
        /// </summary>
        public static string Security_NoAccess {
            get {
                return ResourceManager.GetString("Security_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem trying to load Spring Configuration information for enviroment [{0}].
        /// </summary>
        public static string Spring_ConfigError {
            get {
                return ResourceManager.GetString("Spring_ConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object called {0} cannot be found in the Application Context. Check spelling..
        /// </summary>
        public static string Spring_ObjectNotFound {
            get {
                return ResourceManager.GetString("Spring_ObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sprint_Desc {
            get {
                return ResourceManager.GetString("Sprint_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Sprint_Number {
            get {
                return ResourceManager.GetString("Sprint_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is exceeding normal usage.
        /// </summary>
        public static string Status_AmberMessage {
            get {
                return ResourceManager.GetString("Status_AmberMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calling Martini service - Please stand by ....
        /// </summary>
        public static string Status_CallingMartiniService {
            get {
                return ResourceManager.GetString("Status_CallingMartiniService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing all filters.
        /// </summary>
        public static string Status_ClearingFilters {
            get {
                return ResourceManager.GetString("Status_ClearingFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical.
        /// </summary>
        public static string Status_Critical {
            get {
                return ResourceManager.GetString("Status_Critical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment.
        /// </summary>
        public static string Status_FieldEnvironment {
            get {
                return ResourceManager.GetString("Status_FieldEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are running &apos;{0}&apos; in &apos;{1}&apos; mode. Connected to server {2} on port {3}.
        /// </summary>
        public static string Status_FieldEnvironmentTT {
            get {
                return ResourceManager.GetString("Status_FieldEnvironmentTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in user.
        /// </summary>
        public static string Status_FieldUsername {
            get {
                return ResourceManager.GetString("Status_FieldUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; has successfully logged into &apos;{1}&apos; application..
        /// </summary>
        public static string Status_FieldUsernameTT {
            get {
                return ResourceManager.GetString("Status_FieldUsernameTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Version.
        /// </summary>
        public static string Status_FieldVersion {
            get {
                return ResourceManager.GetString("Status_FieldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos;, the current version of the ADT executable that you are running is &apos;{1}&apos;..
        /// </summary>
        public static string Status_FieldVersionTT {
            get {
                return ResourceManager.GetString("Status_FieldVersionTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtered {0}/{1} rows.
        /// </summary>
        public static string Status_FilteredMessage {
            get {
                return ResourceManager.GetString("Status_FilteredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is running normally.
        /// </summary>
        public static string Status_GreenMessage {
            get {
                return ResourceManager.GetString("Status_GreenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hint:Minimizing and Maximizing the application will rapidly free memory .
        /// </summary>
        public static string Status_Hint {
            get {
                return ResourceManager.GetString("Status_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Status_Normal {
            get {
                return ResourceManager.GetString("Status_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Status_ReadyPrompt {
            get {
                return ResourceManager.GetString("Status_ReadyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System is using more memory then recommended.
        /// </summary>
        public static string Status_RedMessage {
            get {
                return ResourceManager.GetString("Status_RedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trades to process:{0}.
        /// </summary>
        public static string Status_TradesToProcess {
            get {
                return ResourceManager.GetString("Status_TradesToProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Status_Warning {
            get {
                return ResourceManager.GetString("Status_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The named service below timed out: {0}{1}{2} Either re-perform the user action or restart the GUI.
        /// </summary>
        public static string Tibco_TimeoutError {
            get {
                return ResourceManager.GetString("Tibco_TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure grid columns.
        /// </summary>
        public static string TT_ConfigureGrid {
            get {
                return ResourceManager.GetString("TT_ConfigureGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to exit the &apos;{0}&apos; application.
        /// </summary>
        public static string TT_ExitApplication {
            get {
                return ResourceManager.GetString("TT_ExitApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the current grid contents to Excel.
        /// </summary>
        public static string TT_ExportGrid {
            get {
                return ResourceManager.GetString("TT_ExportGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the current active grid.
        /// </summary>
        public static string TT_PrintGrid {
            get {
                return ResourceManager.GetString("TT_PrintGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a print preview of the current grid.
        /// </summary>
        public static string TT_PrintPreviewGrid {
            get {
                return ResourceManager.GetString("TT_PrintPreviewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for information within the grid.
        /// </summary>
        public static string TT_SearchGrid {
            get {
                return ResourceManager.GetString("TT_SearchGrid", resourceCulture);
            }
        }
    }
}
